# Project Description

### objective: 
***customer transaction data from bank to uncover the behavioral insight. use only pandas for data manipulation and seaborn for visualization***

### Domain Explanation

***you work as customer behavioral analyst ata a bank digital analytics department. Your manager has tasked you with finding the pattern in transaction behavioral like fraud detection, spending pattern and financial well being from the data collected from the thousand of customer transactions. Your report will help the bank design better financial products, detect the fraud faster and personalized offers.***

##### Pandas -> processing
##### Seaborn -> Visual story telling

## Column Explanations
- **transaction_id**: Unique ID for each transaction
- **customer_id**: ID mapping to individual customer
- **account_id**: Bank account from which transaction is made
- **transaction_date**: Date and time when transaction occurred
- **posting_date**: Date when transaction was posted to the bank
- **transaction_amount**: Amount debited or credited
- **currency**: Currency of the transaction
- **merchant_id**: Unique identifier for merchant
- **merchant_name**: Name of the business or vendor
- **merchant_category**: Type of goods/service purchased
- **card_issuer**: Issuer bank of the transaction card
- **location_city**: City where transaction took place
- **location_state**: State of transaction
- **location_country**: Country where merchant is located
- **balance_before**: Account balance before transaction
- **balance_after**: Account balance after transaction
- **is_fraud**: Boolean indicator if the transaction was fraudulent
- **customer_since**: Date the customer joined the bank
- **customer_age**: Age of the customer
- **customer_gender**: Gender identity of the customer
- **credit_score**: Credit score of customer
- **reward_points_earned**: Points earned from this transaction

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [3]:
#load the data
data_file = "../Datasets/kaggle/customer_transaction_analysis_data.csv"

df = pd.read_csv(data_file)

In [4]:
df.head(5)

,transaction_id,customer_id,account_id,transaction_date,posting_date,transaction_amount,currency,merchant_id,merchant_name,merchant_category,...,location_state,location_country,balance_before,balance_after,is_fraud,customer_since,customer_age,customer_gender,credit_score,reward_points_earned
0,cfbfff6e-548d-45ab-bd47-c3af21b10774,ae101def-6378-4a57-af2f-13831eb933c6,fced023a-c73b-4051-95ce-0044fee7d58b,2023-06-28T12:23:31.876Z,2022-03-11T10:53:37.841Z,4668.11,BMD,584b02d9-4e0c-4869-8038-7d9395199f66,Feeney and Sons,Home,...,Vermont,China,"$9,162.74",4690.141442,False,2025-06-30T23:06:38.073Z,57,Androgynous,665,145
1,db45f012-a0ee-4a80-a859-491371311b28,486c1800-f83b-4d99-bd8a-6e9747f2fe54,270f0001-fd5f-4fbf-86b1-39844c4d0ecf,2023-03-17T11:22:25.256Z,2023-12-07T18:52:16.361Z,1042.72,VES,84beb445-2c1d-45b3-b2c2-8ff354e17686,Collier - Waters,Toys,...,Alabama,Iran,6748.357564,1941.71734,False,2024-09-03T10:16:15.469Z,23,Transsexual male,735,508
2,2fd4ea51-1374-4341-8890-1a6ecde181c0,3a7f6cca-57bc-4819-bfbe-398e8c133e1a,f6e89d11-a4e6-4677-b8b3-2dd16f5e2ac8,2022-10-15T07:40:35.636Z,2022-11-21T00:18:54.946Z,3428.38,DKK,c02b7600-f2c1-42e7-a935-dd9ce3eea4be,Rogahn - Cartwright,Computers,...,Washington,Senegal,3647.32929,5657.08509,False,2016-02-20T22:08:29.505Z,72,Male to female transgender woman,454,526
3,59a0d00e-c94b-42ff-9021-243b6642afed,81994b75-665c-4176-bd94-be1d93bc1c35,addbbbc0-7c69-4c71-8114-da2cb5b6481b,2022-09-26T06:56:41.344Z,2022-04-07T20:25:06.790Z,1539.85,AFN,3cf64c65-289c-45aa-a4f6-3743fcaa95b1,Goodwin - Homenick,Garden,...,Nebraska,Macao,1435.559207,8541.294285,False,2018-01-31T00:21:14.114Z,53,Agender,694,748
4,b1cd7143-605a-4081-8c14-96d0f6ff531c,ede611a7-9fa8-407f-adf5-911eb37987ac,f8e3a1c2-4dad-477e-9bd3-46c31e4886be,2022-08-08T12:32:45.386Z,2023-04-20T16:57:42.981Z,3146.31,UGX,182755d6-2e60-48c7-8dd4-7425609a6ff3,McClure Inc,Health,...,Georgia,Zimbabwe,4144.677691,8752.950082,False,2018-08-22T01:13:40.050Z,62,Cis man,345,812

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  object
 1   customer_id           100000 non-null  object
 2   account_id            100000 non-null  object
 3   transaction_date      100000 non-null  object
 4   posting_date          100000 non-null  object
 5   transaction_amount    100000 non-null  float64
 6   currency              100000 non-null  object
 7   merchant_id           100000 non-null  object
 8   merchant_name         100000 non-null  object
 9   merchant_category     100000 non-null  object
 10  card_issuer           100000 non-null  object
 11  location_city         100000 non-null  object
 12  location_state        100000 non-null  object
 13  location_country      100000 non-null  object
 14  balance_before        100000 non-null  object
 15  balance_after         100000 non-null  object
 16  is_fraud              100000 non-null  bool
 17  customer_since        100000 non-null  object
 18  customer_age          100000 non-null  int64
 19  customer_gender       100000 non-null  object
 20  credit_score          100000 non-null  int64
 21  reward_points_earned  100000 non-null  int64
dtypes: bool(1), float64(1), int64(3), object(17)
memory usage: 16.1+ MB

#EDA

- Check if all attributes are available or not described in Data Dictionary
- Size of the data
- Sanity Check
- Type checking and Typecasting if required
- Check for the missing values
- Handling the misisng values
- Check for duplicates
- Handle the duplicates
- Check for the outliers
- Handle the outliers
- Encoding (Converting the non-numeric to numeric)
- Correlation
- Analysis

- **Amount- Numeric but in data - object (Typecasting is required)**
- **Transaction Date -> Date type - object (Typecasting is required)**

In [6]:
df.columns

Index(['transaction_id', 'customer_id', 'account_id', 'transaction_date',
       'posting_date', 'transaction_amount', 'currency', 'merchant_id',
       'merchant_name', 'merchant_category', 'card_issuer', 'location_city',
       'location_state', 'location_country', 'balance_before', 'balance_after',
       'is_fraud', 'customer_since', 'customer_age', 'customer_gender',
       'credit_score', 'reward_points_earned'],
      dtype='object')

In [7]:
#size of the data
df.shape

(100000, 22)

 ##### Sanity check
 - Some irrelevant columns are present
 - Some important columns are missing

In [8]:
df.iloc[:15,11:]

,location_city,location_state,location_country,balance_before,balance_after,is_fraud,customer_since,customer_age,customer_gender,credit_score,reward_points_earned
0,Fort Fannieland,Vermont,China,"$9,162.74",4690.141442,False,2025-06-30T23:06:38.073Z,57,Androgynous,665,145
1,Port Elsefurt,Alabama,Iran,6748.357564,1941.71734,False,2024-09-03T10:16:15.469Z,23,Transsexual male,735,508
2,Maxinestad,Washington,Senegal,3647.32929,5657.08509,False,2016-02-20T22:08:29.505Z,72,Male to female transgender woman,454,526
3,Uriahfield,Nebraska,Macao,1435.559207,8541.294285,False,2018-01-31T00:21:14.114Z,53,Agender,694,748
4,South Fay,Georgia,Zimbabwe,4144.677691,8752.950082,False,2018-08-22T01:13:40.050Z,62,Cis man,345,812
5,South Olen,Missouri,Somalia,795.528597,6363.292379,False,2019-09-02T18:28:12.138Z,70,Cisgender man,826,880
6,Eden Prairie,Idaho,Svalbard & Jan Mayen Islands,7455.518879,3401.828605,False,2018-09-04T02:33:44.655Z,82,Male to female transsexual woman,351,343
7,Rodrickworth,Florida,Trinidad and Tobago,8682.908873,9727.93909,False,2018-06-30T01:59:30.572Z,38,Demi-boy,329,359
8,Port Venastad,Indiana,Saint Vincent and the Grenadines,9611.483566,8550.299891,False,2022-11-17T08:32:07.267Z,48,Female to male trans man,663,683
9,Nettieton,Missouri,Mexico,6551.656791,7418.102938,False,2019-02-13T14:56:47.454Z,32,Male to female transgender woman,698,815
10,Riceboro,Kansas,Azerbaijan,4114.420562,8534.516673,False,2020-12-04T15:05:26.765Z,63,Intersex man,323,946
11,Fort Arvelfield,South Carolina,Lesotho,7781.189634,1294.428316,False,2020-09-23T19:04:57.979Z,32,Cis male,411,829
12,Boyleport,Utah,Brunei Darussalam,8538.98142,2248.523416,False,2016-01-16T22:46:39.152Z,73,Male to female,796,678
13,Careyview,Colorado,Greece,8076.19493,$900.92,False,2021-07-21T05:08:15.149Z,58,T* woman,741,860
14,South Beulahside,New York,Iceland,8169.382369,8330.874583,False,2020-05-05T06:00:47.521Z,55,Demi-boy,629,895

#### Type casting

In [9]:
df.dtypes

transaction_id           object
customer_id              object
account_id               object
transaction_date         object
posting_date             object
transaction_amount      float64
currency                 object
merchant_id              object
merchant_name            object
merchant_category        object
card_issuer              object
location_city            object
location_state           object
location_country         object
balance_before           object
balance_after            object
is_fraud                   bool
customer_since           object
customer_age              int64
customer_gender          object
credit_score              int64
reward_points_earned      int64
dtype: object

- transaction_date, posting_date customer_since-> Date
- balnce_before and balance_after -> Numeric

In [13]:
columns_to_date = ["transaction_date", "posting_date", "customer_since"]

for col in columns_to_date:
    df[col] = pd.to_datetime(df[col])

df[columns_to_date].dtypes

transaction_date    datetime64[ns, UTC]
posting_date        datetime64[ns, UTC]
customer_since      datetime64[ns, UTC]
dtype: object

In [14]:
df.dtypes

transaction_id                       object
customer_id                          object
account_id                           object
transaction_date        datetime64[ns, UTC]
posting_date            datetime64[ns, UTC]
transaction_amount                  float64
currency                             object
merchant_id                          object
merchant_name                        object
merchant_category                    object
card_issuer                          object
location_city                        object
location_state                       object
location_country                     object
balance_before                       object
balance_after                        object
is_fraud                               bool
customer_since          datetime64[ns, UTC]
customer_age                          int64
customer_gender                      object
credit_score                          int64
reward_points_earned                  int64
dtype: object

In [22]:
# balance_before and balance_after -> Numeric

def convert_numeric(col):
    df[col] = pd.to_numeric(df[col].replace(r'[^0-9.-]+','',regex=True),errors='coerce')

col_numeric = ['balance_before','balance_after']

for col in col_numeric:
    convert_numeric(col)    

df[col_numeric].dtypes

balance_before    float64
balance_after     float64
dtype: object

In [28]:
# example
dd=pd.DataFrame({'Amt':['4500', '$2500', '', '3,000', '-', '4564.4478', '.', '6000','`-700']})
dd.Amt=dd.Amt.replace(r'[^0-9.-]','',regex=True)

dd

         Amt
0       4500
1       2500
2
3       3000
4          -
5  4564.4478
6          .
7       6000
8       -700

In [29]:
pd.to_numeric(dd.Amt,errors="coerce")

0    4500.0000
1    2500.0000
2          NaN
3    3000.0000
4          NaN
5    4564.4478
6          NaN
7    6000.0000
8    -700.0000
Name: Amt, dtype: float64