In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
master_data = pd.read_csv('../Datasets/kaggle/Indian_Climate_Dataset_2024_2025.csv')

master_data

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%)
0,2024-01-01,Mumbai,Maharashtra,32.5,18.0,25.2,77.6,0.0,3.3,259,Poor,1020.3,62.1
1,2024-01-01,Delhi,Delhi,25.4,10.7,18.1,84.1,0.0,9.0,130,Moderate,1008.4,46.0
2,2024-01-01,Bengaluru,Karnataka,37.2,30.8,34.0,49.0,3.7,6.6,54,Satisfactory,1008.0,61.3
3,2024-01-01,Chennai,Tamil Nadu,37.2,30.4,33.8,34.2,9.5,9.0,176,Moderate,993.4,70.0
4,2024-01-01,Kolkata,West Bengal,27.4,17.5,22.5,32.2,9.1,9.2,97,Satisfactory,1008.2,56.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7305,2025-12-31,Hyderabad,Telangana,41.8,32.8,37.3,65.2,4.2,19.4,95,Satisfactory,1007.0,48.3
7306,2025-12-31,Ahmedabad,Gujarat,37.7,23.5,30.6,76.7,12.7,9.1,173,Moderate,1000.5,49.6
7307,2025-12-31,Jaipur,Rajasthan,44.2,37.6,40.9,74.8,1.2,20.5,329,Very Poor,1006.4,80.0
7308,2025-12-31,Lucknow,Uttar Pradesh,43.7,35.3,39.5,50.3,0.0,7.3,80,Satisfactory,1011.6,45.9
7309,2025-12-31,Bhopal,Madhya Pradesh,37.8,25.8,31.8,53.7,0.0,24.0,157,Moderate,996.7,21.4

In [4]:
master_data.head()

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%)
0,2024-01-01,Mumbai,Maharashtra,32.5,18.0,25.2,77.6,0.0,3.3,259,Poor,1020.3,62.1
1,2024-01-01,Delhi,Delhi,25.4,10.7,18.1,84.1,0.0,9.0,130,Moderate,1008.4,46.0
2,2024-01-01,Bengaluru,Karnataka,37.2,30.8,34.0,49.0,3.7,6.6,54,Satisfactory,1008.0,61.3
3,2024-01-01,Chennai,Tamil Nadu,37.2,30.4,33.8,34.2,9.5,9.0,176,Moderate,993.4,70.0
4,2024-01-01,Kolkata,West Bengal,27.4,17.5,22.5,32.2,9.1,9.2,97,Satisfactory,1008.2,56.9

In [5]:
master_data.tail()

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%)
7305,2025-12-31,Hyderabad,Telangana,41.8,32.8,37.3,65.2,4.2,19.4,95,Satisfactory,1007.0,48.3
7306,2025-12-31,Ahmedabad,Gujarat,37.7,23.5,30.6,76.7,12.7,9.1,173,Moderate,1000.5,49.6
7307,2025-12-31,Jaipur,Rajasthan,44.2,37.6,40.9,74.8,1.2,20.5,329,Very Poor,1006.4,80.0
7308,2025-12-31,Lucknow,Uttar Pradesh,43.7,35.3,39.5,50.3,0.0,7.3,80,Satisfactory,1011.6,45.9
7309,2025-12-31,Bhopal,Madhya Pradesh,37.8,25.8,31.8,53.7,0.0,24.0,157,Moderate,996.7,21.4

In [6]:
master_data.isnull().sum()

Date                    0
City                    0
State                   0
Temperature_Max (°C)    0
Temperature_Min (°C)    0
Temperature_Avg (°C)    0
Humidity (%)            0
Rainfall (mm)           0
Wind_Speed (km/h)       0
AQI                     0
AQI_Category            0
Pressure (hPa)          0
Cloud_Cover (%)         0
dtype: int64

In [7]:
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7310 entries, 0 to 7309
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  7310 non-null   object
 1   City                  7310 non-null   object
 2   State                 7310 non-null   object
 3   Temperature_Max (°C)  7310 non-null   float64
 4   Temperature_Min (°C)  7310 non-null   float64
 5   Temperature_Avg (°C)  7310 non-null   float64
 6   Humidity (%)          7310 non-null   float64
 7   Rainfall (mm)         7310 non-null   float64
 8   Wind_Speed (km/h)     7310 non-null   float64
 9   AQI                   7310 non-null   int64
 10  AQI_Category          7310 non-null   object
 11  Pressure (hPa)        7310 non-null   float64
 12  Cloud_Cover (%)       7310 non-null   float64
dtypes: float64(8), int64(1), object(4)
memory usage: 742.6+ KB

In [8]:
master_data.describe()

,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,Pressure (hPa),Cloud_Cover (%)
count,7310.000000,7310.000000,7310.000000,7310.000000,7310.000000,7310.000000,7310.000000,7310.000000,7310.000000
mean,34.952161,25.006402,29.980192,62.653516,8.231300,13.522763,193.759508,1007.358577,52.630055
std,5.781372,6.476264,5.966698,18.680171,17.758208,6.562729,89.182569,10.109978,27.327729
min,25.000000,10.100000,17.600000,30.000000,0.000000,2.000000,40.000000,990.000000,5.000000
25%,30.000000,19.900000,25.000000,46.400000,0.000000,7.900000,116.000000,998.700000,28.925000
50%,34.900000,25.000000,30.000000,62.700000,0.000000,13.500000,194.000000,1007.300000,52.700000
75%,40.000000,30.000000,35.000000,78.700000,6.300000,19.100000,270.000000,1016.200000,76.200000
max,45.000000,39.800000,42.300000,95.000000,79.900000,25.000000,349.000000,1025.000000,100.000000

In [9]:
master_data.columns

Index(['Date', 'City', 'State', 'Temperature_Max (°C)', 'Temperature_Min (°C)',
       'Temperature_Avg (°C)', 'Humidity (%)', 'Rainfall (mm)',
       'Wind_Speed (km/h)', 'AQI', 'AQI_Category', 'Pressure (hPa)',
       'Cloud_Cover (%)'],
      dtype='object')

In [10]:
master_data.isna().sum()

Date                    0
City                    0
State                   0
Temperature_Max (°C)    0
Temperature_Min (°C)    0
Temperature_Avg (°C)    0
Humidity (%)            0
Rainfall (mm)           0
Wind_Speed (km/h)       0
AQI                     0
AQI_Category            0
Pressure (hPa)          0
Cloud_Cover (%)         0
dtype: int64

In [11]:
master_data["City"].value_counts()

City
Mumbai       731
Delhi        731
Bengaluru    731
Chennai      731
Kolkata      731
Hyderabad    731
Ahmedabad    731
Jaipur       731
Lucknow      731
Bhopal       731
Name: count, dtype: int64

In [12]:
master_data.loc[master_data["State"]=="Karnataka"].head(5)

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%)
2,2024-01-01,Bengaluru,Karnataka,37.2,30.8,34.0,49.0,3.7,6.6,54,Satisfactory,1008.0,61.3
12,2024-01-02,Bengaluru,Karnataka,41.1,27.2,34.2,50.7,0.0,20.8,198,Moderate,1020.1,5.7
22,2024-01-03,Bengaluru,Karnataka,38.2,27.5,32.8,36.1,0.0,24.4,235,Poor,1003.8,89.7
32,2024-01-04,Bengaluru,Karnataka,36.0,23.8,29.9,72.9,2.9,14.8,116,Moderate,1011.4,44.9
42,2024-01-05,Bengaluru,Karnataka,40.8,27.9,34.4,35.9,0.0,12.2,76,Satisfactory,1021.1,38.3

In [13]:
master_data.loc[[master_data["AQI"].idxmax()]]

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%)
120,2024-01-13,Mumbai,Maharashtra,40.2,34.9,37.5,31.4,3.3,17.7,349,Very Poor,1005.6,31.0

In [14]:
listofcities = master_data.groupby("City")

listofcities.groups.keys()

dict_keys(['Ahmedabad', 'Bengaluru', 'Bhopal', 'Chennai', 'Delhi', 'Hyderabad', 'Jaipur', 'Kolkata', 'Lucknow', 'Mumbai'])

In [15]:
listofcities = master_data.groupby("City")

listofcities.get_group("Mumbai")["Temperature_Avg (°C)"].max()

np.float64(42.3)

# Average Rainfall

In [16]:
average_rainfall=master_data.groupby("City")["Rainfall (mm)"].transform("mean")

master_data["Average_Rainfall (mm)"] = average_rainfall

master_data[["City","State","Average_Rainfall (mm)"]]

           City           State  Average_Rainfall (mm)
0        Mumbai     Maharashtra               8.101231
1         Delhi           Delhi               8.277839
2     Bengaluru       Karnataka               7.456498
3       Chennai      Tamil Nadu               7.894938
4       Kolkata     West Bengal               8.378659
...         ...             ...                    ...
7305  Hyderabad       Telangana               8.704104
7306  Ahmedabad         Gujarat               8.457729
7307     Jaipur       Rajasthan               8.527633
7308    Lucknow   Uttar Pradesh               8.255540
7309     Bhopal  Madhya Pradesh               8.258824

[7310 rows x 3 columns]

# Compute monthly average temperature per city.

In [17]:
master_data["Date"].dtype

master_data["Date"] = pd.to_datetime(master_data["Date"])


master_data["YearMonth"] = master_data["Date"].dt.to_period("M")

avg_temp_per_month = master_data.groupby(["City","YearMonth"])["Temperature_Avg (°C)"].mean().reset_index()

avg_temp_per_month = avg_temp_per_month.sort_values(["City","YearMonth"],ascending=[True,False])

avg_temp_per_month.groupby("City").head(3)

          City YearMonth  Temperature_Avg (°C)
23   Ahmedabad   2025-12             28.658065
22   Ahmedabad   2025-11             28.936667
21   Ahmedabad   2025-10             30.761290
47   Bengaluru   2025-12             30.416129
46   Bengaluru   2025-11             29.700000
45   Bengaluru   2025-10             30.248387
71      Bhopal   2025-12             30.538710
70      Bhopal   2025-11             29.863333
69      Bhopal   2025-10             29.864516
95     Chennai   2025-12             28.293548
94     Chennai   2025-11             30.186667
93     Chennai   2025-10             29.919355
119      Delhi   2025-12             27.977419
118      Delhi   2025-11             31.240000
117      Delhi   2025-10             30.993548
143  Hyderabad   2025-12             30.480645
142  Hyderabad   2025-11             31.756667
141  Hyderabad   2025-10             30.129032
167     Jaipur   2025-12             31.225806
166     Jaipur   2025-11             29.650000
165     Jaipur   2025-10             30.570968
191    Kolkata   2025-12             30.045161
190    Kolkata   2025-11             33.053333
189    Kolkata   2025-10             29.941935
215    Lucknow   2025-12             30.325806
214    Lucknow   2025-11             28.140000
213    Lucknow   2025-10             30.516129
239     Mumbai   2025-12             28.054839
238     Mumbai   2025-11             28.973333
237     Mumbai   2025-10             28.377419

# Identify hottest and coldest day per city.

In [18]:
id_hot = master_data.groupby("City")["Temperature_Avg (°C)"].idxmax()

master_data.loc[id_hot].sort_values("City")

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%),Average_Rainfall (mm),YearMonth
5986,2025-08-21,Ahmedabad,Gujarat,44.4,39.1,41.8,52.0,13.6,18.6,203,Poor,1007.7,15.3,8.457729,2025-08
4162,2025-02-20,Bengaluru,Karnataka,44.9,39.7,42.3,49.8,0.0,8.1,161,Moderate,999.0,53.0,7.456498,2025-02
6959,2025-11-26,Bhopal,Madhya Pradesh,44.9,39.3,42.1,90.2,0.0,23.2,236,Poor,1016.6,10.1,8.258824,2025-11
1243,2024-05-04,Chennai,Tamil Nadu,44.7,39.2,42.0,87.6,27.6,13.1,115,Moderate,1001.6,22.2,7.894938,2024-05
4621,2025-04-07,Delhi,Delhi,44.7,39.3,42.0,48.4,0.0,10.1,195,Moderate,999.4,81.3,8.277839,2025-04
1195,2024-04-29,Hyderabad,Telangana,44.9,38.6,41.7,33.2,7.0,17.6,323,Very Poor,1023.4,53.5,8.704104,2024-04
6127,2025-09-04,Jaipur,Rajasthan,44.8,39.2,42.0,70.1,0.0,11.9,148,Moderate,996.5,80.9,8.527633,2025-09
3064,2024-11-02,Kolkata,West Bengal,44.7,39.5,42.1,73.7,0.0,7.2,63,Satisfactory,1005.1,14.1,8.378659,2024-11
1378,2024-05-17,Lucknow,Uttar Pradesh,44.9,39.8,42.3,53.1,0.0,18.3,254,Poor,993.0,75.5,8.255540,2024-05
1470,2024-05-27,Mumbai,Maharashtra,44.9,39.8,42.3,65.2,0.0,14.5,57,Satisfactory,1006.5,30.5,8.101231,2024-05

In [19]:
id_cold = master_data.groupby("City")["Temperature_Avg (°C)"].idxmin()

master_data.loc[id_cold].sort_values("City")

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%),Average_Rainfall (mm),YearMonth
4106,2025-02-14,Ahmedabad,Gujarat,25.3,11.3,18.3,91.5,0.0,10.0,336,Very Poor,1016.6,39.0,8.457729,2025-02
1552,2024-06-04,Bengaluru,Karnataka,25.1,10.2,17.7,53.7,0.0,20.3,199,Moderate,1014.8,55.1,7.456498,2024-06
5369,2025-06-20,Bhopal,Madhya Pradesh,25.0,10.3,17.7,31.7,0.0,21.2,101,Moderate,1005.7,57.0,8.258824,2025-06
1003,2024-04-10,Chennai,Tamil Nadu,25.1,10.3,17.7,87.1,0.0,22.6,70,Satisfactory,1000.2,58.5,7.894938,2024-04
1,2024-01-01,Delhi,Delhi,25.4,10.7,18.1,84.1,0.0,9.0,130,Moderate,1008.4,46.0,8.277839,2024-01
3455,2024-12-11,Hyderabad,Telangana,25.7,10.8,18.3,93.7,0.0,9.6,308,Very Poor,1003.0,76.1,8.704104,2024-12
47,2024-01-05,Jaipur,Rajasthan,25.2,10.5,17.9,32.8,46.9,3.7,202,Poor,1009.4,97.1,8.527633,2024-01
3734,2025-01-08,Kolkata,West Bengal,25.0,10.1,17.6,43.7,0.0,20.4,212,Poor,1024.2,86.7,8.378659,2025-01
3248,2024-11-20,Lucknow,Uttar Pradesh,25.1,10.9,18.0,34.3,9.4,14.3,114,Moderate,1007.7,11.9,8.255540,2024-11
6920,2025-11-23,Mumbai,Maharashtra,25.1,10.2,17.7,70.7,9.9,12.6,179,Moderate,990.3,85.7,8.101231,2025-11

In [20]:
hottest_days=master_data.loc[id_hot].sort_values("City")
coldest_days=master_data.loc[id_cold].sort_values("City")

extreme_days = pd.concat(
    [
        hottest_days.assign(Type="Hottest"),
        coldest_days.assign(Type="Coldest")
    ]
).sort_values(["City", "Type"])


extreme_days

,Date,City,State,Temperature_Max (°C),Temperature_Min (°C),Temperature_Avg (°C),Humidity (%),Rainfall (mm),Wind_Speed (km/h),AQI,AQI_Category,Pressure (hPa),Cloud_Cover (%),Average_Rainfall (mm),YearMonth,Type
4106,2025-02-14,Ahmedabad,Gujarat,25.3,11.3,18.3,91.5,0.0,10.0,336,Very Poor,1016.6,39.0,8.457729,2025-02,Coldest
5986,2025-08-21,Ahmedabad,Gujarat,44.4,39.1,41.8,52.0,13.6,18.6,203,Poor,1007.7,15.3,8.457729,2025-08,Hottest
1552,2024-06-04,Bengaluru,Karnataka,25.1,10.2,17.7,53.7,0.0,20.3,199,Moderate,1014.8,55.1,7.456498,2024-06,Coldest
4162,2025-02-20,Bengaluru,Karnataka,44.9,39.7,42.3,49.8,0.0,8.1,161,Moderate,999.0,53.0,7.456498,2025-02,Hottest
5369,2025-06-20,Bhopal,Madhya Pradesh,25.0,10.3,17.7,31.7,0.0,21.2,101,Moderate,1005.7,57.0,8.258824,2025-06,Coldest
6959,2025-11-26,Bhopal,Madhya Pradesh,44.9,39.3,42.1,90.2,0.0,23.2,236,Poor,1016.6,10.1,8.258824,2025-11,Hottest
1003,2024-04-10,Chennai,Tamil Nadu,25.1,10.3,17.7,87.1,0.0,22.6,70,Satisfactory,1000.2,58.5,7.894938,2024-04,Coldest
1243,2024-05-04,Chennai,Tamil Nadu,44.7,39.2,42.0,87.6,27.6,13.1,115,Moderate,1001.6,22.2,7.894938,2024-05,Hottest
1,2024-01-01,Delhi,Delhi,25.4,10.7,18.1,84.1,0.0,9.0,130,Moderate,1008.4,46.0,8.277839,2024-01,Coldest
4621,2025-04-07,Delhi,Delhi,44.7,39.3,42.0,48.4,0.0,10.1,195,Moderate,999.4,81.3,8.277839,2025-04,Hottest
3455,2024-12-11,Hyderabad,Telangana,25.7,10.8,18.3,93.7,0.0,9.6,308,Very Poor,1003.0,76.1,8.704104,2024-12,Coldest
1195,2024-04-29,Hyderabad,Telangana,44.9,38.6,41.7,33.2,7.0,17.6,323,Very Poor,1023.4,53.5,8.704104,2024-04,Hottest
47,2024-01-05,Jaipur,Rajasthan,25.2,10.5,17.9,32.8,46.9,3.7,202,Poor,1009.4,97.1,8.527633,2024-01,Coldest
6127,2025-09-04,Jaipur,Rajasthan,44.8,39.2,42.0,70.1,0.0,11.9,148,Moderate,996.5,80.9,8.527633,2025-09,Hottest
3734,2025-01-08,Kolkata,West Bengal,25.0,10.1,17.6,43.7,0.0,20.4,212,Poor,1024.2,86.7,8.378659,2025-01,Coldest
3064,2024-11-02,Kolkata,West Bengal,44.7,39.5,42.1,73.7,0.0,7.2,63,Satisfactory,1005.1,14.1,8.378659,2024-11,Hottest
3248,2024-11-20,Lucknow,Uttar Pradesh,25.1,10.9,18.0,34.3,9.4,14.3,114,Moderate,1007.7,11.9,8.255540,2024-11,Coldest
1378,2024-05-17,Lucknow,Uttar Pradesh,44.9,39.8,42.3,53.1,0.0,18.3,254,Poor,993.0,75.5,8.255540,2024-05,Hottest
6920,2025-11-23,Mumbai,Maharashtra,25.1,10.2,17.7,70.7,9.9,12.6,179,Moderate,990.3,85.7,8.101231,2025-11,Coldest
1470,2024-05-27,Mumbai,Maharashtra,44.9,39.8,42.3,65.2,0.0,14.5,57,Satisfactory,1006.5,30.5,8.101231,2024-05,Hottest

# Find number of rainy days per city (Rainfall > 0).

In [21]:
rain_fall = master_data[master_data["Rainfall (mm)"]>0].groupby("City").size()

rain_fall.reset_index(name="Rainfall days")

        City  Rainfall days
0  Ahmedabad            302
1  Bengaluru            291
2     Bhopal            313
3    Chennai            293
4      Delhi            280
5  Hyderabad            304
6     Jaipur            285
7    Kolkata            317
8    Lucknow            307
9     Mumbai            292

# Compare weekday vs weekend average AQI per city.

In [22]:
master_data["Date"] = pd.to_datetime(master_data["Date"])

master_data["DateType"] = np.where(
    master_data["Date"].dt.weekday<5,"weekday","weekend"
)


daysGroupAQI = master_data.groupby(["City","DateType"])["AQI"].mean()

daysGroupAQI = daysGroupAQI.reset_index()


daysGroupAQI_Pivot = daysGroupAQI.pivot(index="City",columns="DateType",values="AQI").reset_index().round(2)

daysGroupAQI_Pivot

DateType       City  weekday  weekend
0         Ahmedabad   196.26   187.61
1         Bengaluru   189.32   197.08
2            Bhopal   198.43   207.55
3           Chennai   200.70   194.02
4             Delhi   195.66   190.65
5         Hyderabad   194.08   188.47
6            Jaipur   188.21   193.65
7           Kolkata   191.85   188.60
8           Lucknow   199.02   194.91
9            Mumbai   191.64   176.01

# Calculate average, max, and min rainfall per city (Dont consider 0 rain fall).

In [23]:
master_data_grp = master_data[master_data["Rainfall (mm)"]!=0].groupby("City")["Rainfall (mm)"]


master_data_grp.mean().reset_index().round(2)

        City  Rainfall (mm)
0  Ahmedabad          20.47
1  Bengaluru          18.73
2     Bhopal          19.29
3    Chennai          19.70
4      Delhi          21.61
5  Hyderabad          20.93
6     Jaipur          21.87
7    Kolkata          19.32
8    Lucknow          19.66
9     Mumbai          20.28

In [24]:
master_data_grp.max().reset_index()

        City  Rainfall (mm)
0  Ahmedabad           79.9
1  Bengaluru           79.1
2     Bhopal           79.3
3    Chennai           79.2
4      Delhi           79.7
5  Hyderabad           79.9
6     Jaipur           79.8
7    Kolkata           79.6
8    Lucknow           79.4
9     Mumbai           79.8

In [25]:
master_data_grp.min().reset_index()

        City  Rainfall (mm)
0  Ahmedabad            0.1
1  Bengaluru            0.1
2     Bhopal            0.2
3    Chennai            0.2
4      Delhi            0.2
5  Hyderabad            0.1
6     Jaipur            0.3
7    Kolkata            0.1
8    Lucknow            0.2
9     Mumbai            0.2